CREATE SEQUENCE COMPANIES_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS COMPANIES
(
    ID             int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME           varchar(20),
    FOUNDED_DATE   timestamp,
    NO_OF_EMPLOYEE int
)